### ISSUE TITLE
Inertia crashing upon loading a world or joining a server

### ISSUE THREAD

**Issue by rvb00t** [THEREALWWEFAN231/Inertia#1025]
**Inertia Utility Mod version:** 3.1.3
**Minecraft version:** 1.16.4
**Operating system:** Windows 10
**Optifine/Other mods:** None

**What's the issue:** 

Upon joining a world or loading a server, Inertia crashes. It loads the world and once it gets to the "Saving world" part, it crashes.
Also tried with the 1.15.2 version, same result.
No luck downgrading to fabric 0.10.4 either.

**Crash-report(if applicable)(Would be very useful also please format):**

```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 15/01/21, 15:50
Description: Unexpected error

java.lang.IllegalStateException: java.lang.NullPointerException
	at inertia.ZGbt.pAcb(Unknown Source)
	at net.minecraft.class_757.handler$zbp000$KhDo(class_757.java:971)
	at net.minecraft.class_757.method_3188(class_757.java:751)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.lang.NullPointerException
	... 14 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at inertia.ZGbt.pAcb(Unknown Source)
	at net.minecraft.class_757.handler$zbp000$KhDo(class_757.java:971)
	at net.minecraft.class_757.method_3188(class_757.java:751)

-- Affected level --
Details:
	All players: 1 total; [class_746['Gagliardini'/244, l='ClientLevel', x=-122.50, y=63.00, z=3.50]]
	Chunk stats: Client Chunk Cache: 1369, 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (-133,63,8), Chunk: (at 11,3,8 in -9,0; contains blocks -144,0,0 to -129,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 28 game time, 28 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 15.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 421648888 bytes (402 MB) / 1011875840 bytes (965 MB) up to 1073741824 bytes (1024 MB)
	CPUs: 16
	JVM Flags: 5 total; -Xmx1G -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	Launched Version: fabric-loader-0.11.0-1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2080 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.79, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
```

**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [x] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by THEREALWWEFAN231** [comment]
Told him this in discord, if anyone else is wondering, 

"You are using java 15, Inertia crashes with java 12 and above, so install java 8 and make the fabric profile use that java version"
