### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ZylyxI** [THEREALWWEFAN231/Inertia#1055]
**latest:** 
**1.16.4:** 
**Operating system: Windows** 
**Optifine/Other mods: None ** 

**What's the issue:** 
Game keeps crashing giving me a -1 or 0 code.
**Crash-report(if applicable)(Would be very useful also please format):**
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 1/25/21 8:12 PM
Description: Initializing game

unacceptable code point ' ' (0x0) special characters are not allowed
in "'reader'", position 0
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:211)
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176)
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171)
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126)
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1177)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:287)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:195)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:118)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
	at us.myles.ViaVersion.util.Config.loadConfig(Config.java:59)
	at us.myles.ViaVersion.util.Config.reloadConfig(Config.java:120)
	at nl.matsv.viabackwards.ViaBackwardsConfig.reloadConfig(ViaBackwardsConfig.java:24)
	at nl.matsv.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:56)
	at inertia.KtQs.uAYg(Unknown Source)
	at inertia.KgQm.FhPM(Unknown Source)
	at inertia.JKdr.xcpU(Unknown Source)
	at net.minecraft.class_310.handler$zzc000$LePc(class_310.java:3381)
	at net.minecraft.class_310.<init>(class_310.java:592)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:211)
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176)
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171)
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126)
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1177)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:287)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:195)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:118)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
	at us.myles.ViaVersion.util.Config.loadConfig(Config.java:59)
	at us.myles.ViaVersion.util.Config.reloadConfig(Config.java:120)
	at nl.matsv.viabackwards.ViaBackwardsConfig.reloadConfig(ViaBackwardsConfig.java:24)
	at nl.matsv.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:56)
	at inertia.KtQs.uAYg(Unknown Source)
	at inertia.KgQm.FhPM(Unknown Source)
	at inertia.JKdr.xcpU(Unknown Source)
	at net.minecraft.class_310.handler$zzc000$LePc(class_310.java:3381)
	at net.minecraft.class_310.<init>(class_310.java:592)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
        at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
**Final checklist:**
The Fabric loader works fine when inertia is not in the mods. 
- [ ] I know how to properly use check boxes 
- [ ] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [ ] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by Godeps2891** [comment]
pinned in the discord
unacceptable code point ' ' (0x0) special characters are not allowed in "'reader'", position 0

Caused by corrupted ViaVersion configs
Go to your .minecraft folder -> Inertia Folder -> Version Folder and delete the ViaVersion folder

**Comment by ZylyxI** [comment]
Ah, I see thank you for the help.
