### ISSUE TITLE
ClickGui problem

### ISSUE THREAD

**Issue by jmdevcz** [THEREALWWEFAN231/Inertia#1113]
**Inertia Utility Mod version:3.1.3
**Minecraft version:1.16.5
**Operating system:Windows 10 x64
**Optifine/Other mods:No

**What's the issue:
Everytime i open clickgui, game crashes.

**Crash-report(if applicable)(Would be very useful also please format):

`[15:24:16] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:24:16] [main/INFO]: [STDOUT]: Baritone world data dir: C:\Users\janma\AppData\Roaming\.minecraft\baritone\moriasmp.aternos.me
[15:24:16] [main/INFO]: [STDOUT]: Cached world directory: C:\Users\janma\AppData\Roaming\.minecraft\baritone\moriasmp.aternos.me\cache
[15:24:16] [main/INFO]: [STDOUT]: Would save waypoints to C:\Users\janma\AppData\Roaming\.minecraft\baritone\moriasmp.aternos.me\waypoints
[15:24:16] [main/WARN]: Unknown custom packed identifier: minecraft:register
[15:24:17] [main/INFO]: [CHAT] Welcome to VELL!
[15:24:17] [main/INFO]: [CHAT] Hello!
[15:24:17] [pool-4-thread-1/INFO]: [STDOUT]: Loading region -1,-2 from disk C:\Users\janma\AppData\Roaming\.minecraft\baritone\moriasmp.aternos.me\cache
[15:24:17] [pool-4-thread-1/INFO]: [STDERR]: java.io.EOFException: Unexpected end of ZLIB input stream
[15:24:17] [pool-4-thread-1/INFO]: [STDERR]: 	at java.util.zip.InflaterInputStream.fill(Unknown Source)
[15:24:17] [pool-4-thread-1/INFO]: [STDERR]: 	at java.util.zip.InflaterInputStream.read(Unknown Source)
[15:24:17] [pool-4-thread-1/INFO]: [STDERR]: 	at java.util.zip.GZIPInputStream.read(Unknown Source)
[15:24:17] [pool-4-thread-1/INFO]: [STDERR]: 	at java.util.zip.InflaterInputStream.read(Unknown Source)
[15:24:17] [pool-4-thread-1/INFO]: [STDERR]: 	at java.io.DataInputStream.readInt(Unknown Source)
[15:24:17] [pool-4-thread-1/INFO]: [STDERR]: 	at baritone.l.b(Unknown Source)
[15:24:17] [pool-4-thread-1/INFO]: [STDERR]: 	at baritone.m.a(Unknown Source)
[15:24:17] [pool-4-thread-1/INFO]: [STDERR]: 	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.computeIfAbsent(Long2ObjectOpenHashMap.java:479)
[15:24:17] [pool-4-thread-1/INFO]: [STDERR]: 	at baritone.m.b(Unknown Source)
[15:24:17] [pool-4-thread-1/INFO]: [STDERR]: 	at baritone.m.a(Unknown Source)
[15:24:17] [pool-4-thread-1/INFO]: [STDERR]: 	at baritone.o.run(Unknown Source)
[15:24:17] [pool-4-thread-1/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[15:24:17] [pool-4-thread-1/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[15:24:17] [pool-4-thread-1/INFO]: [STDERR]: 	at java.lang.Thread.run(Unknown Source)
[15:24:18] [main/INFO]: Loaded 301 advancements
[15:24:18] [main/INFO]: [CHAT] Welcome, MC0268!
[15:24:18] [main/INFO]: [CHAT] Type /help for a list of commands.
[15:24:18] [main/INFO]: [CHAT] Type /list to see who else is online.
[15:24:18] [main/INFO]: [CHAT] Players online: 2 - World time: 2:52 AM
[15:24:18] [main/INFO]: [CHAT] You have no new mail.
[15:24:18] [main/INFO]: [CHAT] §3[IRC] §rSuccessfully connected to the irc server, you can now send messages by typing in chat, @ + your message
[15:24:18] [main/INFO]: [CHAT] §3[IRC] §rReminder to read and follow the rules, type "@-rules" to view them
`
**Final checklist:**

- [ X] I know how to properly use check boxes 
- [ X] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [ X] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by THEREALWWEFAN231** [comment]
Did you set a Custom Font? 
![image](https://user-images.githubusercontent.com/21975901/110220194-c4ed6680-7e78-11eb-9c34-44565ebc15d4.png)
Feel free to reopen/comment if this doesn't work.
