### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SkidFace** [THEREALWWEFAN231/Inertia#1188]
**Inertia Utility Mod version: 1.16.5** 
**Minecraft version: 1.16.5** 
**Operating system: Windows 10** 
**Optifine/Other mods: N/A** 

**What's the issue: Game crashes upon clicking anything in the Waypoint GUI or resizing window while in Waypoint GUI. Also, the sizing is weird and some buttons do not appear. ** 

**Crash-report(if applicable)(Would be very useful also please format) Description: 

Unexpected error

java.lang.NullPointerException: Unexpected error
	at inertia.plJl.tQLe(Unknown Source)
	at inertia.plJl.method_25426(Unknown Source)
	at net.minecraft.class_437.method_25423(class_437.java:325)
	at net.minecraft.class_437.method_25410(class_437.java:430)
	at net.minecraft.class_310.method_15993(class_310.java:1151)
	at net.minecraft.class_1041.method_4504(class_1041.java:268)
	at net.minecraft.class_1041$$Lambda$2430/1533086864.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWFramebufferSizeCallbackI.callback(GLFWFramebufferSizeCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:109)
	at net.minecraft.class_1041.method_15998(class_1041.java:308)
	at net.minecraft.class_310.method_1523(class_310.java:1068)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at inertia.plJl.tQLe(Unknown Source)
	at inertia.plJl.method_25426(Unknown Source)
	at net.minecraft.class_437.method_25423(class_437.java:325)
	at net.minecraft.class_437.method_25410(class_437.java:430)
	at net.minecraft.class_310.method_15993(class_310.java:1151)
	at net.minecraft.class_1041.method_4504(class_1041.java:268)
	at net.minecraft.class_1041$$Lambda$2430/1533086864.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWFramebufferSizeCallbackI.callback(GLFWFramebufferSizeCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:109)
**

**Final checklist:**

- [x] I know how to properly use check boxes 
- [X] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [X] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by THEREALWWEFAN231** [comment]
This is fixed in the next release(when ever that is), thank you for reporting the bug though.
