### ISSUE TITLE
inertia crashed with pixelmon

### ISSUE THREAD

**Issue by FreeHK-Lunity** [THEREALWWEFAN231/Inertia#1233]
**Inertia Utility Mod version:** 3.1.3
**Minecraft version:** 1.12.2
**Operating system:** Windows 10 Build 19041, 20H2
**Optifine/Other mods:** jei, optifine, pixelmon, journeymap,veinminer,gravestone
**Launcher:** normal

**What's the bug:**  Minecraft crashed with pixelmon installed

**Crash-report(if applicable)(located in .minecraft/latest.log):**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  KDgB (Inertia Client 3.1.3 - 1.12.2.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/21/21 11:16 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraft.block.Block.handler$tXVm$zda000(Block.java:2761)
	at net.minecraft.block.Block.func_149645_b(Block.java)
	at com.pixelmonmod.pixelmon.client.ClientProxy.fixModelDefs(ClientProxy.java:328)
	at com.pixelmonmod.pixelmon.config.RegistryListener.onRegisterItems(RegistryListener.java:92)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_24_RegistryListener_onRegisterItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.Block.handler$tXVm$zda000(Block.java:2761)
	at net.minecraft.block.Block.func_149645_b(Block.java)
	at com.pixelmonmod.pixelmon.client.ClientProxy.fixModelDefs(ClientProxy.java:328)
	at com.pixelmonmod.pixelmon.config.RegistryListener.onRegisterItems(RegistryListener.java:92)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_24_RegistryListener_onRegisterItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1214708080 bytes (1158 MB) / 1610612736 bytes (1536 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_F5 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version      | Source                                    | Signature                                |
	|:----- |:------------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2       | minecraft.jar                             | None                                     |
	| LCH   | mcp                 | 9.42         | minecraft.jar                             | None                                     |
	| LCH   | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2855.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge               | 14.23.5.2855 | forge-1.12.2-14.23.5.2855.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | inertia             | 3.1.3        | Inertia Client 3.1.3 - 1.12.2.jar         | None                                     |
	| LCH   | jei                 | 4.15.0.296   | jei_1.12.2-4.15.0.296.jar                 | None                                     |
	| LCH   | pixelmon            | 8.2.0        | Pixelmon-1.12.2-8.2.0-universal.jar       | None                                     |
	| LCH   | gravestone          | 1.10.3       | 墓碑gravestone-1.10.3.jar                   | None                                     |
	| LCH   | journeymap          | 1.12.2-5.7.1 | 小地圖journeymap-1.12.2-5.7.1-tw.jar         | None                                     |
	| LCH   | veinminer           | 0.38.2       | 連鎖挖礦VeinMiner-1.12-0.38.2.647+b31535a.jar | None                                     |
	| LCH   | veinminermodsupport | 0.38.2       | 連鎖挖礦VeinMiner-1.12-0.38.2.647+b31535a.jar | None                                     |

	Loaded coremods (and transformers): 
KDgB (Inertia Client 3.1.3 - 1.12.2.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 24.20.100.6344' Renderer: 'Intel(R) UHD Graphics 630'
	Launched Version: 1.12.2-forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 630 GL version 4.5.0 - Build 24.20.100.6344, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: !   ��1��7��lIronwork - 16x
	Current Language: English (Canada)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 24.20.100.6344
	OpenGlRenderer: Intel(R) UHD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 12

**Final checklist:**
- [x] I know how to properly use check boxes. 
- [X] I have tried to reproduce this bug after removing all other mods, including Optifine or Sodium. 
- [X] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by Paralusion** [comment]
We don't support modpacks
