### ISSUE TITLE
Inertia Crash 1.16.5

### ISSUE THREAD

**Issue by Alexevier** [THEREALWWEFAN231/Inertia#1292]
**Inertia Utility Mod version:** 3.1.3
**Minecraft version:** 1.16.5 (fabric-loader 1.12.5
**Operating system:** Debian-11 x64, Kernel 5.10.0-9-amd64, KDE Plasma 5.20, KDE Frameworks 5.78.0
**Optifine/Other mods:** Bunch of performance mods and lithematica
**Launcher:** Launcher Fenix 7 v5.7.9
**If helps the hardaware is:** Core 2 Quad Q6600, Graphics Intel Mesa DRI G45/G43 (opengl2.1)
**Java Version:** 17.0.1 LTS

**What's the bug:** It crashes when loading a singleplayer world or conecting to a server. Even tried desactivating every single option on the click gui and running only the client with the fabric api (0.42.0).

**Crash-report(if applicable)(located in .minecraft/latest.log):** I Pasted it because for some reason i can't attach the file. The report is when connecting to 7b7t.me without any extra mod, not even the fabric api.
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 11/27/21, 1:55 AM
Description: Unexpected error

java.lang.IllegalStateException: java.lang.NullPointerException
	at inertia.UETq.ayOT(Unknown Source)
	at net.minecraft.class_757.handler$zdc000$nmgn(class_757.java:971)
	at net.minecraft.class_757.method_3188(class_757.java:751)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at inertia.UETq.ayOT(Unknown Source)
	at net.minecraft.class_757.handler$zdc000$nmgn(class_757.java:971)
	at net.minecraft.class_757.method_3188(class_757.java:751)

-- Affected level --
Details:
	All players: 1 total; [class_746['Alexevier1'/42590, l='ClientLevel', x=-2310746.39, y=63.00, z=1393322.84]]
	Chunk stats: Client Chunk Cache: 18225, 49
	Level dimension: minecraft:overworld
	Level spawn location: World: (156,64,248), Chunk: (at 12,4,8 in 9,15; contains blocks 144,0,240 to 159,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 57150 game time, 18457273 day time
	Server brand: §6[§b7b§37t§6] 1.8.x to 1.17.x§r
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.10.0-9-amd64
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1185134592 bytes (1130 MB) / 2153775104 bytes (2054 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 4
	JVM Flags: 5 total; -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:+IgnoreUnrecognizedVMOptions
	Launched Version: fabric-loader-0.12.5-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Mesa DRI Intel(R) G45/G43 (ELK) GL version 2.1 Mesa 20.3.5, Intel Open Source Technology Center
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	GPU Warnings: version: 2.1
	Graphics mode: fast
	Resource Packs: vanilla, programer_art, file/VanillaTweaks - Alexevier.zip, file/No Pumpkin Overlay.zip, file/Black Nether Bricks.zip
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM)2 Quad CPU Q6600 @ 2.40GHz

**Final checklist:**
- [x] I know how to properly use check boxes. 
- [x] I have tried to reproduce this bug after removing all other mods, including Optifine or Sodium. 
- [x] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by Alexevier** [comment]
The solution was use Java-8
