### ISSUE TITLE
Inertia not opening with pixelmon

### ISSUE THREAD

**Issue by ZzPSYCHOzZ** [THEREALWWEFAN231/Inertia#1340]
Inertia Utility Mod version: 1.12.2 - 3.1.3
Minecraft version: 1.12.2
Operating system: Windows
Optifine/Other mods: Pixelmon

What's the bug: Crashing on startup

Crash-report(if applicable)(located in .minecraft/latest.log):
fice---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  KDgB (Inertia Client 3.1.3 - 1.12.2.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 8/18/23 9:35 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraft.block.Block.handler$tXVm$zda000(Block.java:2761)
	at net.minecraft.block.Block.func_149645_b(Block.java)
	at com.pixelmonmod.pixelmon.client.ClientProxy.fixModelDefs(ClientProxy.java:372)
	at com.pixelmonmod.pixelmon.config.RegistryListener.onRegisterItems(RegistryListener.java:92)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_14_RegistryListener_onRegisterItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.Block.handler$tXVm$zda000(Block.java:2761)
	at net.minecraft.block.Block.func_149645_b(Block.java)
	at com.pixelmonmod.pixelmon.client.ClientProxy.fixModelDefs(ClientProxy.java:372)
	at com.pixelmonmod.pixelmon.config.RegistryListener.onRegisterItems(RegistryListener.java:92)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_14_RegistryListener_onRegisterItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 200184408 bytes (190 MB) / 536870912 bytes (512 MB) up to 4143972352 bytes (3952 MB)
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx3946m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version                  | Source                                | Signature                                |
	|:----- |:------------------- |:------------------------ |:------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2                   | minecraft.jar                         | None                                     |
	| LCH   | mcp                 | 9.42                     | minecraft.jar                         | None                                     |
	| LCH   | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2860.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge               | 14.23.5.2860             | forge-1.12.2-14.23.5.2860.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | waila               | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar           | None                                     |
	| LCH   | inertia             | 3.1.3                    | Inertia Client 3.1.3 - 1.12.2.jar     | None                                     |
	| LCH   | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar              | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | jei                 | 4.15.0.275               | JEI.jar                               | None                                     |
	| LCH   | journeymap          | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar           | None                                     |
	| LCH   | mousetweaks         | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar         | None                                     |
	| LCH   | pixelmon            | 8.4.3                    | Pixelmon-1.12.2-8.4.3-universal.jar   | None                                     |
	| LCH   | tcg                 | 1.12.2-8.4.3-universal   | Pixelmon-1.12.2-8.4.3-universal.jar   | None                                     |
	| LCH   | wailaharvestability | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
KDgB (Inertia Client 3.1.3 - 1.12.2.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.5161' Renderer: 'Intel(R) HD Graphics 2500'
	Launched Version: 1.12.2-forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 2500 GL version 4.0.0 - Build 10.18.10.5161, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Smooth Font.zip, Visual+Painting+Items+1.19.4.zip, [1.3]+Enhanced+Boss+Bars.zip, Brewing+Guide.zip, 3d-breaking.zip, Rainbow+Outlines.zip, astraliyte-s-animated-texturesv1-2.zip, §bBetter§3Ores§f-§91.19.4§0.zip, colourful-containers-dark-mode-e290.zip, Icons+v.1.8.zip, UniqueDark_1.20.1.zip, xali's+Enchanted+Books+v0.12.0.zip, §eTorches§8-§eReimagined§0_§8[v1.3.1]§0.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 5
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.5161
	OpenGlRenderer: Intel(R) HD Graphics 2500
	OpenGlVendor: Intel
	CpuCount: 4

Final checklist:
- [x] I know how to properly use check boxes. 
- [x] I have tried to reproduce this bug after removing all other mods, including Optifine or Sodium. 
- [x] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by Realswitzer** [comment]
skill issue

**Comment by ZzPSYCHOzZ** [comment]
Nah, i just want to dupe in a p2w server

**Comment by Weigurde** [comment]
:3
