### ISSUE TITLE
Inventory cleaner crash

### ISSUE THREAD

**Issue by BenCat07** [THEREALWWEFAN231/Inertia#476]
**WWE version:** 
3.0.4
**Minecraft version:** 
1.15
**Operating system:** 
Linux
**Optifine/Other mods:** 
Wurst (disabled though)

**Whats the issue:** 
Crash  when using inventory cleaner and grabbing item to be cleaned from hopper

**Crash-report(Would be very useful also please format):**
```java.lang.IndexOutOfBoundsException: Index: 43, Size: 41
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at net.minecraft.class_1703.method_7593(class_1703.java:383)
	at net.minecraft.class_636.method_2906(class_636.java:393)
	at wwe.oLzn.arsS(Unknown Source)
	at net.minecraft.class_746.handler$zkb000$sPXU(class_746.java:1743)
	at net.minecraft.class_746.method_5773(class_746.java)
	at net.minecraft.class_638.method_18646(class_638.java:180)
	at net.minecraft.class_1937.method_18472(class_1937.java:534)
	at net.minecraft.class_638.method_18116(class_638.java:151)
	at net.minecraft.class_310.method_1574(class_310.java:1467)
	at net.minecraft.class_310.method_1523(class_310.java:964)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)```

**Comment by Paralusion** [comment]
probably fixed?
