### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by AlKapwn** [THEREALWWEFAN231/Inertia#488]
**WWE version:** 3.0.4
**Minecraft version:** 1.12.2
**Operating system:** Win 8.1
**Optifine/Other mods:** Just WWE, but also crashing with Optifine+Impact added

**Whats the issue:** Trying to load into any singleplayer/multiplayer world and the game crashes once terrain is generated and the screen changes to your player from the world loading screen.

**Crash-report(Would be very useful also please format):** 

22:25:18.327
game
[22:25:18] [Server thread/WARN] [minecraft/WorldServer]: Keeping entity minecraft:slime that already exists with UUID 07dd05b1-4c31-49da-a184-0eed7ff05c9f
22:25:18.338
game
[22:25:18] [Server thread/WARN] [minecraft/WorldServer]: Keeping entity minecraft:slime that already exists with UUID 1d0975b9-4526-4f69-858d-4d4dec672836
22:25:18.721
game
[22:25:18] [Server thread/INFO] [FML]: Unloading dimension -1
22:25:18.741
game
[22:25:18] [Server thread/INFO] [FML]: Unloading dimension 1
22:25:18.743
game
[22:25:18] [Server thread/INFO] [minecraft/IntegratedServer]: Changing view distance to 6, from 10
22:25:20.702
game
[22:25:20] [Netty Local Client IO #0/INFO] [FML]: Server protocol version 2
22:25:20.710
game
[22:25:20] [Netty Server IO #1/INFO] [FML]: Client protocol version 2
22:25:20.712
game
[22:25:20] [Netty Server IO #1/INFO] [FML]: Client attempting to join with 5 mods : minecraft@1.12.2,FML@8.0.99.99,wwe@3.0.4,forge@14.23.5.2768,mcp@9.42
22:25:20.735
game
[22:25:20] [Netty Local Client IO #0/INFO] [FML]: [Netty Local Client IO #0] Client side modded connection established
22:25:20.747
game
[22:25:20] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
22:25:20.761
game
[22:25:20] [Server thread/INFO] [minecraft/PlayerList]: Al_Kapwn[local:E:27bc2f9b] logged in with entity id 187 at (-847.0219443785788, 4.0, -248.33843737674673)
22:25:20.813
game
[22:25:20] [Server thread/INFO] [minecraft/MinecraftServer]: Al_Kapwn joined the game
22:25:21.878
game
[22:25:21] [main/INFO] [STDOUT]: [baritone.v:a:-1]: Baritone world data dir: C:\Users\Al Kapwn\AppData\Roaming\.minecraft\saves\New World\baritone\DIM0
22:25:21.908
game
[22:25:21] [main/INFO] [STDOUT]: [baritone.n:<init>:-1]: Cached world directory: C:\Users\Al Kapwn\AppData\Roaming\.minecraft\saves\New World\baritone\DIM0\cache
22:25:21.918
game
[22:25:21] [main/INFO] [STDOUT]: [baritone.t:<init>:-1]: Would save waypoints to C:\Users\Al Kapwn\AppData\Roaming\.minecraft\saves\New World\baritone\DIM0\waypoints
22:25:21.928
game
[22:25:21] [Server thread/INFO] [minecraft/IntegratedServer]: Saving and pausing game...
22:25:21.948
game
[22:25:21] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'New World'/overworld
22:25:22.117
game
[22:25:22] [Thread-13/INFO] [STDERR]: [wwe.PVaa:run:-1]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://wweclient.com/DonationCenter.php
22:25:22.117
game
[22:25:22] [Thread-13/INFO] [STDERR]: [wwe.PVaa:run:-1]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
22:25:22.117
game
[22:25:22] [Thread-13/INFO] [STDERR]: [wwe.PVaa:run:-1]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
22:25:22.117
game
[22:25:22] [Thread-13/INFO] [STDERR]: [wwe.PVaa:run:-1]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
22:25:22.117
game
[22:25:22] [Thread-13/INFO] [STDERR]: [wwe.PVaa:run:-1]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
22:25:22.117
game
[22:25:22] [Thread-13/INFO] [STDERR]: [wwe.PVaa:run:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
22:25:22.118
game
[22:25:22] [Thread-13/INFO] [STDERR]: [wwe.PVaa:run:-1]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
22:25:22.118
game
[22:25:22] [Thread-13/INFO] [STDERR]: [wwe.PVaa:run:-1]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
22:25:22.118
game
[22:25:22] [Thread-13/INFO] [STDERR]: [wwe.PVaa:run:-1]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
22:25:22.118
game
[22:25:22] [Thread-13/INFO] [STDERR]: [wwe.PVaa:run:-1]: 	at wwe.PVaa.run(Unknown Source)
22:25:23.327
game
[22:25:23] [pool-4-thread-1/INFO] [STDOUT]: [baritone.m:b:-1]: Loading region -2,-1 from disk C:\Users\Al Kapwn\AppData\Roaming\.minecraft\saves\New World\baritone\DIM0\cache
22:25:23.435
game
[22:25:23] [main/INFO] [minecraft/AdvancementList]: Loaded 35 advancements
22:25:24.000
game
[22:25:23] [pool-4-thread-1/INFO] [STDOUT]: [baritone.m:b:-1]: Loaded region successfully in 673ms

**Comment by THEREALWWEFAN231** [comment]
That is not the crash log/full crash log, also I do not recommend WWE with impact or any other major client, it causes things to happen that are not suppose to(but send the full crash log just for me to see).

**Comment by Paralusion** [comment]
probably due to combining with impact
