### ISSUE TITLE
my game crashes on opening

### ISSUE THREAD

**Issue by tylerdino** [THEREALWWEFAN231/Inertia#663]
**Inertia Utility Mod version:** 
**Minecraft version:** 
**Operating system:** 
**Optifine/Other mods:** 

**What's the issue:** 

java.lang.NoClassDefFoundError: us/myles/ViaVersion/api/platform/ViaInjector
	at inertia.ysbw.TCGw(Unknown Source)
	at inertia.jxrw.wktw(Unknown Source)
	at net.minecraft.class_310.handler$zzd000$wRXS(class_310.java:2812)
	at net.minecraft.class_310.<init>(class_310.java:578)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.ClassNotFoundException: us.myles.ViaVersion.api.platform.ViaInjector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at inertia.ysbw.TCGw(Unknown Source)
	at inertia.jxrw.wktw(Unknown Source)
	at net.minecraft.class_310.handler$zzd000$wRXS(class_310.java:2812)
	at net.minecraft.class_310.<init>(class_310.java:578)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1160855016 bytes (1107 MB) / 2046820352 bytes (1952 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.9.1+build.205-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 580 Series GL version 4.6.13559 Compatibility Profile Context 26.20.12028.2, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 4x AMD A8-7670K Radeon R7, 10 Compute Cores 4C+6G

**Comment by THEREALWWEFAN231** [comment]
What inertia version is this?

**Comment by tylerdino** [comment]
1.16.1

**Comment by tylerdino** [comment]
> What inertia version is this?

1.16.1

**Comment by THEREALWWEFAN231** [comment]
i mean like 3.1, 3.1.1?

**Comment by tylerdino** [comment]
3.1.1

**Comment by THEREALWWEFAN231** [comment]
RIP, go to your .minecraft folder and delete the inertia folder, start minecraft.

**Comment by tylerdino** [comment]
So can I use it like if I re-downlode It

**Comment by THEREALWWEFAN231** [comment]
You dont need to redownload, just deleting the inertia folder will work.

**Comment by tylerdino** [comment]
It still don’t work

**Comment by tylerdino** [comment]
Can u add a different file I could try and use ?

**Comment by tylerdino** [comment]
On here

**Comment by THEREALWWEFAN231** [comment]
Do you have discord, add me THEREALWWEFAN#2157

**Comment by tylerdino** [comment]
Ok
