### ISSUE TITLE
Crashes when i open the client.

### ISSUE THREAD

**Issue by ghost** [THEREALWWEFAN231/Inertia#80]
- **WWE version:** 2.7.2
- **Minecraft version:** 1.12.2 (i also tried the 1.13 version)
- **Launcher version:** 2.1.54.10
- **Operating system:** Debian Linux (10, sid)
- **Java version:** 8 (also tried 9, 10 and 11)
- **Optifine/Other mods:** None

**Whats the issue:** 
Crashes when i open the client.
It can go to the forge loading screen, but before the loading screen is done, it crashes.

**Crash-report:**
```java
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from wwe (wwe)
```
```java
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoader (wwe.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 7/11/19 9:03 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from wwe (wwe)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -65536000
	at sun.font.FileFontStrike.setCachedGlyphPtr(FileFontStrike.java:520)
	at sun.font.FileFontStrike.setCachedGlyphPtr(FileFontStrike.java:537)
	at sun.font.FileFontStrike.getSlot0GlyphImagePtrs(FileFontStrike.java:449)
	at sun.font.CompositeStrike.getGlyphImagePtrs(CompositeStrike.java:115)
	at sun.font.GlyphList.mapChars(GlyphList.java:272)
	at sun.font.GlyphList.setFromString(GlyphList.java:244)
	at sun.java2d.pipe.GlyphListPipe.drawString(GlyphListPipe.java:71)
	at sun.java2d.pipe.ValidatePipe.drawString(ValidatePipe.java:165)
	at sun.java2d.SunGraphics2D.drawString(SunGraphics2D.java:2928)
	at wwe.yfok.FmBz(Unknown Source)
	at wwe.yfok.mdVC(Unknown Source)
	at wwe.yfok.<init>(Unknown Source)
	at wwe.giQz.hQSM(Unknown Source)
	at wwe.giQz.<init>(Unknown Source)
	at wwe.bozE.JduO(Unknown Source)
	at wwe.vlwv.JHOS(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.19.0-5-amd64
	Java Version: 1.8.0_40, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 248854088 bytes (237 MB) / 738197504 bytes (704 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                        | Signature                                |
	|:----- |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHI  | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| UCHI  | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| UCHI  | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | forge     | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHEE | wwe       | 2.7.2        | wwe.jar                       | None                                     |

	Loaded coremods (and transformers): 
MixinLoader (wwe.jar)
  
	GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '3.0 Mesa 18.3.6' Renderer: 'Mesa DRI Intel(R) Ivybridge Desktop '
```

**Comment by Paralusion** [comment]
does this also happen when you launch Forge without WWE?

**Comment by LickTheCheese** [comment]
no, it does not happen.

**Comment by Paralusion** [comment]
I do not see why this is happening, this does not seem to be an issue with my Linux enviremont. I can't see anything of importance that could've caused the crash here.

**Comment by Paralusion** [comment]
probably fixed
