### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by partyanimal** [THEREALWWEFAN231/Inertia#822]
**Inertia Utility Mod version:** 
**Minecraft version:1.16.3 
**Operating system: windows 10
**Optifine/Other mods:** fabric api, fabricmod voxelmap 

**What's the issue:**game crashes on startup even when only using inertia 

**Crash-report(Would be very useful also please format):**
[22:26:31] [main/INFO]: Loading for game Minecraft 1.16.3
[22:26:32] [ForkJoinPool-1-worker-2/WARN]: The mod "inertia" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 7 column 9
- Unsupported root entry "initializers" at line 18 column 17
[22:26:32] [main/INFO]: [FabricLoader] Loading 4 mods: minecraft@1.16.3, mm@2.0.1, inertia@1.16.3, fabricloader@0.10.5+build.213
[22:26:32] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/jonas/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[22:26:33] [main/FATAL]: Mixin apply failed mixins.inertia.json:MmJq -> net.minecraft.class_742: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("RETURN") selector (cancellable = true) Found @Inject targetting a constructor in injector net/minecraft/class_742::ZJdm [PREINJECT Applicator Phase -> mixins.inertia.json:MmJq -> Prepare Injections ->  -> handler$zzc000$ZJdm(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("RETURN") selector (cancellable = true) Found @Inject targetting a constructor in injector net/minecraft/class_742::ZJdm [PREINJECT Applicator Phase -> mixins.inertia.json:MmJq -> Prepare Injections ->  -> handler$zzc000$ZJdm(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.addTargetNode(CallbackInjector.java:405) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:241) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.10.5+build.213.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.10.5+build.213.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.10.5+build.213.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_51]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) [?:1.8.0_51]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) [?:1.8.0_51]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:163) [fabric-loader-0.10.5+build.213.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.minecraft.class_2246.<clinit>(class_2246.java:125) [intermediary-fabric-loader-0.10.5+build.213-1.16.3.jar:?]
	at net.minecraft.class_3523.<clinit>(class_3523.java:13) [intermediary-fabric-loader-0.10.5+build.213-1.16.3.jar:?]
	at net.minecraft.class_5471.<clinit>(class_5471.java:11) [intermediary-fabric-loader-0.10.5+build.213-1.16.3.jar:?]
	at net.minecraft.class_5458.method_30573(class_5458.java:44) [intermediary-fabric-loader-0.10.5+build.213-1.16.3.jar:?]
	at net.minecraft.class_5458$$Lambda$177/1506938939.get(Unknown Source) [intermediary-fabric-loader-0.10.5+build.213-1.16.3.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:75) [intermediary-fabric-loader-0.10.5+build.213-1.16.3.jar:?]
	at net.minecraft.class_5458$$Lambda$185/696165690.accept(Unknown Source) [intermediary-fabric-loader-0.10.5+build.213-1.16.3.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676) [?:1.8.0_51]
	at net.minecraft.class_5458.<clinit>(class_5458.java:74) [intermediary-fabric-loader-0.10.5+build.213-1.16.3.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:237) [intermediary-fabric-loader-0.10.5+build.213-1.16.3.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) [intermediary-fabric-loader-0.10.5+build.213-1.16.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) [intermediary-fabric-loader-0.10.5+build.213-1.16.3.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.5+build.213.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.10.5+build.213.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.10.5+build.213.jar:?]

**Comment by THEREALWWEFAN231** [comment]
Just had someone else have this issue, install this fabric loader version and try it, https://cdn.discordapp.com/attachments/770416854639968327/770420763458666506/unknown.png
Ill have to test out why it doesn't work on the newest fabric loader version

**Comment by Expora09** [comment]
I have tried it, it works (the newest)

**Comment by 0H4rl3qu1n0** [comment]
Doesn't work for me either the keybinds or anything else doesn't work either like the .toggle or any thing like it.

**Comment by THEREALWWEFAN231** [comment]
> Doesn't work for me either the keybinds or anything else doesn't work either like the .toggle or any thing like it.

That would not be caused by this issue, that would be caused by other mods, try just using inertia(in your mods folder), I'm sure the issue won't be there anymore.

**Comment by 0H4rl3qu1n0** [comment]
Would Colormatic change something? (makes it possible to change hardcoded colors in minecraft)

**Comment by 0H4rl3qu1n0** [comment]
https://paste.mod.gg/ikocezamuq.css
it seems to spam this just before finishing loading.

**Comment by 0H4rl3qu1n0** [comment]
ok i disabled everything except for inertia
and now the client wont run

**Comment by 0H4rl3qu1n0** [comment]
nvm i accidentally turned fabric API off aswell

**Comment by THEREALWWEFAN231** [comment]
Fabric API isn't needed, message me on discord(if you have it) THEREALWWEFAN#2157

**Comment by 0H4rl3qu1n0** [comment]
Message couldn't be delivered

**Comment by THEREALWWEFAN231** [comment]
Friend me, I can accept, and you can send messages.

**Comment by ycMia** [comment]
It's a problem of VoxelMap, I've succeeded in launch that after I removed VoxelMap from my mod folder.
Please close this issue if the problem is done.
