### ISSUE TITLE
[Bug] Unable to enter worlds on Arch Linux.

### ISSUE THREAD

**Issue by rhearmas** [THEREALWWEFAN231/Inertia#956]
**Inertia Utility Mod version:** Latest (3.1)
**Minecraft version:** 1.16.4
**Operating system:** Arch Linux 2020.11 using kernel 5.9.12-zen
**Optifine/Other mods:** No other mods. No Optifine.

**What's the issue:** I'm unable to enter worlds. I can get to the main menu and navigate through everything there just fine, but once I try to enter a world, once it says that I'm trying to enter the world, it saves and exits the game, giving me the logs posted below.

**Crash report:**
```
[L] Launching Minecraft...
[L] Starting Minecraft fabric-loader-0.10.8-1.16.4
[L] Launching in: /home/rhearmas/Minecraft
[L] Processing post-launch actions. Assist launch: true
===============================================================================================
[19:29:02] [main/INFO]: Loading for game Minecraft 1.16.4
[19:29:02] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[19:29:07] [ForkJoinPool-1-worker-5/WARN]: The mod "inertia" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 7 column 9
- Unsupported root entry "initializers" at line 18 column 17
[19:29:07] [main/INFO]: [FabricLoader] Loading 4 mods: minecraft@1.16.4, mm@2.0.1, inertia@1.16.4, fabricloader@0.10.8
[19:29:07] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/rhearmas/Minecraft/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
Inertia Client is still using the traditional Early Riser initialisation
[19:29:10] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:29:11] [main/INFO]: Setting user: rhearmas
[19:29:11] [main/INFO]: Definitely not up to no good
[19:29:11] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[19:29:15] [main/WARN]: ERROR : Couldn't load Narrator library : Unable to load library 'fliteWrapper': Native library (linux-x86-64/libfliteWrapper.so) not found in resource path (/home/rhearmas/Minecraft/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar:/home/rhearmas/Minecraft/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar:/home/rhearmas/Minecraft/libraries/net/fabricmc/tiny-remapper/0.3.0.70/tiny-remapper-0.3.0.70.jar:/home/rhearmas/Minecraft/libraries/net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar:/home/rhearmas/Minecraft/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar:/home/rhearmas/Minecraft/libraries/com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar:/home/rhearmas/Minecraft/libraries/org/ow2/asm/asm/9.0/asm-9.0.jar:/home/rhearmas/Minecraft/libraries/org/ow2/asm/asm-analysis/9.0/asm-analysis-9.0.jar:/home/rhearmas/Minecraft/libraries/org/ow2/asm/asm-commons/9.0/asm-commons-9.0.jar:/home/rhearmas/Minecraft/libraries/org/ow2/asm/asm-tree/9.0/asm-tree-9.0.jar:/home/rhearmas/Minecraft/libraries/org/ow2/asm/asm-util/9.0/asm-util-9.0.jar:/home/rhearmas/Minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar:/home/rhearmas/Minecraft/libraries/net/fabricmc/intermediary/1.16.4/intermediary-1.16.4.jar:/home/rhearmas/Minecraft/libraries/net/fabricmc/fabric-loader/0.10.8/fabric-loader-0.10.8.jar:/home/rhearmas/Minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:/home/rhearmas/Minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar:/home/rhearmas/Minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:/home/rhearmas/Minecraft/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar:/home/rhearmas/Minecraft/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar:/home/rhearmas/Minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:/home/rhearmas/Minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar:/home/rhearmas/Minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/home/rhearmas/Minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar:/home/rhearmas/Minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/home/rhearmas/Minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/home/rhearmas/Minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/home/rhearmas/Minecraft/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar:/home/rhearmas/Minecraft/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar:/home/rhearmas/Minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:/home/rhearmas/Minecraft/libraries/com/mojang/authlib/2.0.27/authlib-2.0.27.jar:/home/rhearmas/Minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/home/rhearmas/Minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/home/rhearmas/Minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/home/rhearmas/Minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/home/rhearmas/Minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar:/home/rhearmas/Minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar:/home/rhearmas/Minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar:/home/rhearmas/Minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar:/home/rhearmas/Minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar:/home/rhearmas/Minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar:/home/rhearmas/Minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar:/home/rhearmas/Minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar:/home/rhearmas/Minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar:/home/rhearmas/Minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar:/home/rhearmas/Minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar:/home/rhearmas/Minecraft/versions/fabric-loader-0.10.8-1.16.4/fabric-loader-0.10.8-1.16.4.jar)
[19:29:15] [main/INFO]: Reloading ResourceManager: Default, hurt
[19:29:16] [main/INFO]: [STDOUT]: Baritone settings file not found, resetting.
[19:29:30] [main/INFO]: [STDERR]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[19:29:30] [main/INFO]: [STDERR]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[19:29:30] [main/INFO]: [STDERR]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "Thread-8" [19:29:30] [Thread-8/INFO]: [STDERR]: java.lang.NoClassDefFoundError: org/scijava/nativelib/JniExtractor
[19:29:30] [Thread-8/INFO]: [STDERR]: 	at java.base/java.lang.Class.forName0(Native Method)
[19:29:30] [Thread-8/INFO]: [STDERR]: 	at java.base/java.lang.Class.forName(Class.java:340)
[19:29:30] [Thread-8/INFO]: [STDERR]: 	at org.newsclub.net.unix.NativeUnixSocket.<clinit>(NativeUnixSocket.java:35)
[19:29:30] [Thread-8/INFO]: [STDERR]: 	at org.newsclub.net.unix.AFUNIXSocket.<init>(AFUNIXSocket.java:36)
[19:29:30] [Thread-8/INFO]: [STDERR]: 	at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:54)
[19:29:30] [Thread-8/INFO]: [STDERR]: 	at com.jagrosh.discordipc.entities.pipe.UnixPipe.<init>(UnixPipe.java:45)
[19:29:30] [Thread-8/INFO]: [STDERR]: 	at com.jagrosh.discordipc.entities.pipe.Pipe.createPipe(Pipe.java:163)
[19:29:30] [Thread-8/INFO]: [STDERR]: 	at com.jagrosh.discordipc.entities.pipe.Pipe.openPipe(Pipe.java:67)
[19:29:30] [Thread-8/INFO]: [STDERR]: 	at com.jagrosh.discordipc.IPCClient.connect(IPCClient.java:116)
[19:29:30] [Thread-8/INFO]: [STDERR]: 	at inertia.ziXj.run(Unknown Source)
[19:29:30] [Thread-8/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: org.scijava.nativelib.JniExtractor
[19:29:30] [Thread-8/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
[19:29:30] [Thread-8/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
[19:29:30] [Thread-8/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[19:29:30] [Thread-8/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
[19:29:30] [Thread-8/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[19:29:30] [Thread-8/INFO]: [STDERR]: 	... 10 more
[19:29:30] [pool-6-thread-1/INFO]: [STDOUT]: Tried connecting to the irc
[19:29:31] [main/INFO]: [STDOUT]: This isent good, please report this on the github, https://github.com/THEREALWWEFAN231/Inertia/issues field name checkForUpdates not found
[19:29:32] [Via-Mappingloader-0/INFO]: Loading 1.12 -> 1.13 mappings...
[19:29:32] [Via-Mappingloader-1/INFO]: Loading 1.13 -> 1.13.2 mappings...
[19:29:32] [Via-Mappingloader-2/INFO]: Loading 1.13.2 -> 1.14 mappings...
[19:29:32] [Via-Mappingloader-3/INFO]: Loading 1.14 -> 1.15 mappings...
[19:29:32] [Via-Mappingloader-4/INFO]: Loading 1.15 -> 1.16 mappings...
[19:29:32] [Via-Mappingloader-5/INFO]: Loading 1.16 -> 1.16.2 mappings...
[19:29:32] [Via-Mappingloader-0/INFO]: Loading block connection mappings ...
[19:29:32] [main/INFO]: Loading translations...
[19:29:33] [main/INFO]: Registering protocols...
[19:29:33] [Via-Mappingloader-2/INFO]: Loading 1.13 -> 1.12 mappings...
[19:29:33] [Via-Mappingloader-0/INFO]: Loading 1.13.2 -> 1.13 mappings...
[19:29:33] [Via-Mappingloader-0/INFO]: Loading 1.14 -> 1.13.2 mappings...
[19:29:33] [Via-Mappingloader-0/INFO]: Loading 1.15 -> 1.14 mappings...
[19:29:33] [Via-Mappingloader-0/INFO]: Loading 1.16 -> 1.15 mappings...
[19:29:33] [Via-Mappingloader-2/INFO]: Loading 1.16.2 -> 1.16 mappings...
[19:29:34] [ViaVersion-0/WARN]: There is a newer version available: 3.2.1, you're on: 3.2.0
[19:29:34] [ViaVersion-0/INFO]: ViaVersion detected server version: 1.16.4(754)
[19:29:34] [ViaVersion-0/INFO]: Shutting down mapping loader executor!
[19:29:34] [main/INFO]: [STDOUT]: This isent good, please report this on the github, https://github.com/THEREALWWEFAN231/Inertia/issues field name LIGHTING not found
[19:29:34] [main/INFO]: [STDOUT]: This isent good, please report this on the github, https://github.com/THEREALWWEFAN231/Inertia/issues field name state not found
[19:29:34] [main/INFO]: [STDOUT]: This isent good, please report this on the github, https://github.com/THEREALWWEFAN231/Inertia/issues field name cuboids not found
[19:29:34] [main/INFO]: [STDOUT]: This isent good, please report this on the github, https://github.com/THEREALWWEFAN231/Inertia/issues field name sides not found
[19:29:34] [main/INFO]: OpenAL initialized.
[19:29:34] [main/INFO]: Sound engine started
[19:29:35] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[19:29:35] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[19:29:35] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[19:29:35] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[19:29:35] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[19:29:35] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[19:29:35] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[19:29:37] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[19:29:37] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[19:29:37] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[19:29:42] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[19:29:42] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[19:29:42] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[19:29:42] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[19:29:42] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[19:29:42] [main/INFO]: Reloading ResourceManager: Default
[19:29:43] [main/INFO]: Loaded 7 recipes
[19:29:43] [main/INFO]: Loaded 927 advancements
[19:29:46] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:29:46] [Server thread/INFO]: Starting integrated minecraft server version 1.16.4
[19:29:46] [Server thread/INFO]: Generating keypair
[19:29:46] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[19:29:47] [main/INFO]: Preepayrin spawn ayyrea: 0%
[19:29:47] [main/INFO]: Preepayrin spawn ayyrea: 0%
[19:29:47] [main/INFO]: Preepayrin spawn ayyrea: 0%
[19:29:48] [main/INFO]: Time elapsed: 1347 ms
[19:29:48] [Server thread/INFO]: Changing view distance to 11, from 10
[19:29:49] [Server thread/INFO]: rhearmas[local:E:652eb0eb] logged in with entity id 261 at (232.9601209790477, 64.0625, -128.23651978785784)
[19:29:49] [Server thread/INFO]: rhearmas joind teh gaem
[19:29:49] [main/INFO]: [STDOUT]: Baritone world data dir: /home/rhearmas/Minecraft/saves/16_1_16/./baritone
[19:29:49] [main/INFO]: [STDOUT]: Cached world directory: /home/rhearmas/Minecraft/saves/16_1_16/./baritone/cache
[19:29:49] [main/INFO]: [STDOUT]: Would save waypoints to /home/rhearmas/Minecraft/saves/16_1_16/./baritone/waypoints
[19:29:49] [Server thread/INFO]: Saving and pausing game...
[19:29:49] [Server thread/INFO]: Saving chunks for level 'ServerLevel[16.2.1258]'/minecraft:overworld
[19:29:49] [pool-4-thread-1/INFO]: [STDOUT]: Loading region 0,-1 from disk /home/rhearmas/Minecraft/saves/16_1_16/./baritone/cache
[19:29:49] [main/WARN]: Received passengers for unknown entity
[19:29:49] [Server thread/INFO]: Saving chunks for level 'ServerLevel[16.2.1258]'/minecraft:the_nether
[19:29:49] [Server thread/INFO]: Saving chunks for level 'ServerLevel[16.2.1258]'/minecraft:the_end
[19:29:49] [main/INFO]: [STDERR]: java.lang.NullPointerException
[19:29:49] [main/INFO]: [STDERR]: 	at inertia.ZGbt.pAcb(Unknown Source)
[19:29:49] [main/INFO]: [STDERR]: 	at net.minecraft.class_757.handler$zbp000$KhDo(class_757.java:971)
[19:29:49] [main/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3188(class_757.java:751)
[19:29:49] [main/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3192(class_757.java:546)
[19:29:49] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1048)
[19:29:49] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:681)
[19:29:49] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:215)
[19:29:49] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:29:49] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:29:49] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:29:49] [main/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[19:29:49] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
[19:29:49] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
[19:29:49] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
[19:29:50] [main/FATAL]: Unreported exception thrown!
java.lang.IllegalStateException: java.lang.NullPointerException
	at inertia.ZGbt.pAcb(Unknown Source) ~[Inertia%20Client%203.1.3%20-%201.16.4.jar:?]
	at net.minecraft.class_757.handler$zbp000$KhDo(class_757.java:971) ~[intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:751) ~[intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:546) ~[intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1048) ~[intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8.jar:?]
Caused by: java.lang.NullPointerException
	... 14 more
[19:29:50] [Server thread/INFO]: Stopping server
[19:29:50] [Server thread/INFO]: Saving players
[19:29:50] [pool-4-thread-1/INFO]: [STDOUT]: Loaded region successfully in 1020ms
[19:29:50] [Server thread/INFO]: rhearmas lost connection: CYA
[19:29:50] [Server thread/INFO]: rhearmas leeft teh gaem
[19:29:50] [Server thread/INFO]: Stopping singleplayer server as player logged out
[19:29:50] [Server thread/INFO]: Saving worlds
[19:29:50] [Server thread/INFO]: Saving chunks for level 'ServerLevel[16.2.1258]'/minecraft:overworld
[19:29:50] [pool-4-thread-1/INFO]: [STDOUT]: Loading region 0,0 from disk /home/rhearmas/Minecraft/saves/16_1_16/./baritone/cache
[19:29:50] [Server thread/INFO]: ThreadedAnvilChunkStorage (16_1_16): All chunks are saved
[19:29:50] [Server thread/INFO]: Saving chunks for level 'ServerLevel[16.2.1258]'/minecraft:the_nether
[19:29:50] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[19:29:50] [Server thread/INFO]: Saving chunks for level 'ServerLevel[16.2.1258]'/minecraft:the_end
[19:29:50] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[19:29:50] [Server thread/INFO]: ThreadedAnvilChunkStorage (16_1_16): All chunks are saved
[19:29:50] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[19:29:50] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 12/16/20, 7:29 PM
Description: Unexpected error

java.lang.IllegalStateException: java.lang.NullPointerException
	at inertia.ZGbt.pAcb(Unknown Source)
	at net.minecraft.class_757.handler$zbp000$KhDo(class_757.java:971)
	at net.minecraft.class_757.method_3188(class_757.java:751)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.lang.NullPointerException
	... 14 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at inertia.ZGbt.pAcb(Unknown Source)
	at net.minecraft.class_757.handler$zbp000$KhDo(class_757.java:971)
	at net.minecraft.class_757.method_3188(class_757.java:751)

-- Affected level --
Details:
	All players: 1 total; [class_746['rhearmas'/261, l='ClientLevel', x=232.96, y=64.06, z=-128.24]]
	Chunk stats: Client Chunk Cache: 841, 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (240,64,-144), Chunk: (at 0,4,0 in 15,-9; contains blocks 240,0,-144 to 255,255,-129), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 2995921 game time, 3305843 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (amd64) version 5.9.12-zen1-1-zen
	Java Version: 14.0.2, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 555919040 bytes (530 MB) / 1409286144 bytes (1344 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 10 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:ConcGCThreads=2 -XX:ParallelGCThreads=8 -Xmx2048M -Xss1M
	Launched Version: fabric-loader-0.10.8-1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce MX250/PCIe/SSE2 GL version 4.6.0 NVIDIA 455.45.01, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/hurt (incompatible)
	Current Language: LOLCAT (Kingdom of Cats)
	CPU: 8x Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
#@!@# Game crashed! Crash report saved to: #@!@# /home/rhearmas/Minecraft/crash-reports/crash-2020-12-16_19.29.51-client.txt
[19:29:51] [pool-4-thread-1/INFO]: [STDOUT]: Loaded region successfully in 491ms
AL lib: (EE) alc_cleanup: 1 device not closed
[L] Launcher stopped.
[L] Minecraft closed with exit code: 255 (0xff)
```

**Other information:**
I've done my research on Google, on the FAQ page on the website, and through the other issues posted here. I've tried going through the other solutions users had, to no effect. I'm able to run Minecraft in any other client (vanilla, Optifine only, and through the Meteor and WURST clients.

**Comment by THEREALWWEFAN231** [comment]
Java Version: 14.0.2, N/A
Please use a java 8 version, Inertia crashes in java 11 or 12+.

**Comment by THEREALWWEFAN231** [comment]
As said in the FAQ section of the website, once you installed a java 8 version
Open the minecraft launcher, edit the installation used to run Inertia Client(it could be forge or fabric), click the more options button and in the java executable path select the java version you just installed, it should be in the bin folder, probably called java.

**Comment by Godeps2891** [comment]
> probably called java.


99% sure it's java**w**

**Comment by feliscatusmeows** [comment]
The minecraft launcher sometimes has issues when selecting a java runtime and uses another java runtime on linux. Also I'm pretty sure it should be javaw not java

**Comment by rhearmas** [comment]
I installed Java 8 at first, and it didn't change anything. Looks like I forgot to set the version Arch used with `archlinux-java set`. I'll update this with my results.

**Comment by rhearmas** [comment]
Update: mission accomplished. Thanks for referring me to the FAQ, @THEREALWWEFAN231. Guess I was blind enough to not notice that.

For any other Arch users having this issue, run `archlinux-java set java-8-jre/jre` in your terminal to set the version that your device uses. If that doesn't work, install `jre8` and `jdk8` from the AUR using your favorite helper.
